# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Angular-web-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install
        run: npm install

      - name: Inject Secrets into Environment
        env:
          APP_INSIGHTS_CONN: ${{ secrets.APP_INSIGHTS_CONNECTION_STRING }}
        run: |
          node -e "const fs = require('fs'); let c = fs.readFileSync('src/environments/environment.ts', 'utf8'); c = c.replace('#{APP_INSIGHTS_CONNECTION_STRING}#', process.env.APP_INSIGHTS_CONN.trim()); fs.writeFileSync('src/environments/environment.ts', c);"

      - name: npm run build and test
        run: |
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/demo-app-service/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Angular-web-demo'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E050245F259947ADA559D2430A4530CE }}